library(igraph)
library(ActivePathways)
library(data.table)

# VisEvents

getDataFromGMT <- function(gmt) {
  lens <- numeric(length = length(names(gmt)))
  ids <- character(length = length(names(gmt)))
  pathwayNames <- character(length = length(names(gmt)))
  # add data to different vectors
  for (i in seq_along(names(gmt))) {
    name <- names(gmt)[i]
    lens[i] <- length(gmt[[name]]$genes)
    ids[i] <- gmt[[name]]$id
    pathwayNames[i] <- gmt[[name]]$name
  }
  return(list(ids = ids, 
              pathwayNames = pathwayNames, 
              lengths = lens))
}

computeSimilarityCoefficient <- function(metric, intersectionSet, unionSet, genes1, genes2, k) {
  if (metric == "jaccard") {
    return(length(intersectionSet) / length(unionSet))
  } else if (metric == "overlap") {
    return(length(intersectionSet) / min(length(unionSet), length(genes2)))
  } else {
    intersectionLength <- length(intersectionSet)
    jaccard <- intersectionLength / length(unionSet)
    overlap <- intersectionLength / min(length(unionSet), length(genes2))
    return(k * overlap) + ((1 - k) * jaccard)
  }
}


computeSCMatrix <- function(algorithm, gmt, ids, k) {
  simiScoreMatrix <- matrix(ncol = length(ids), 
                            nrow = length(ids), 
                            dimnames = list(ids, 
                                            ids)
  )
  # initiate Matrix storing similarity score between gene sets
  simiScoreMatrix <- matrix(ncol = length(ids), 
                            nrow = length(ids), 
                            dimnames = list(ids, 
                                            ids)
  )
  
  # calculate similarity score and store them in the gene sets
  for (i in seq_along(ids)) {
    for (j in seq_along(ids)) {
      genes1 <- gmt[[ids[i]]]$genes
      genes2 <- gmt[[ids[j]]]$genes
      simiScoreMatrix[ids[i], ids[j]] <- computeSimilarityCoefficient(algorithm, 
                                                                      intersect(genes1, genes2), 
                                                                      union(genes1, genes2), 
                                                                      genes1, 
                                                                      genes2, 
                                                                      k = k)
    }
  }
  print("simiScoreMatrix1")
  print(simiScoreMatrix)
  return(simiScoreMatrix)
}

plotSimiScoreMatrix <- function(simiScoreMatrix, similarityCutoff, pvalueCutoff, lens, pathwayNames, pathways) {
  # remove similaity Score less than the cutoff
  simiScoreMatrix[simiScoreMatrix < similarityCutoff] = 0
  
  # remove self-loop
  for (i in seq_along(rownames(scMatrix))) {
    if (scMatrix[i, i] == 1) {
      simiScoreMatrix[i, i] = 0
    }
  }
  # simiScoreMatrix[simiScoreMatrix == 1] = 0
  print("simiScoreMatrix2")
  print(simiScoreMatrix)
  
  # make colnames, rownames to pathway name instead of id
  colnames(simiScoreMatrix) <- pathwayNames
  rownames(simiScoreMatrix) <- pathwayNames
  # Create igraph object
  mode(simiScoreMatrix) <- "numeric"
  g2 <- igraph::graph.adjacency(simiScoreMatrix, mode = "undirected", weighted = TRUE)
  
  # set vertex size as the size of gene sets
  V(g2)$size <- lens * 0.05 + 4
  # set edge thickness (width) as the weight of edge (similarity score)
  E(g2)$width <- E(g2)$weight * 2
  
  # color
  # get a vector of pathway names ordered by p.val
  orderedPathways <- pathways[order(adjusted.p.val)]$term.name
  # get position of vertex in ordered Pathways
  position <- match(V(g2)$name, orderedPathways)
  # get color based on position
  heatColors <- heat.colors(length(V(g2)))[position]
  V(g2)$color <- heatColors
  
  # apply force-directed layout algorithm by Fruchterman and Reingold
  layout_with_fr(g2) 
  # plot
  return(g2)
} 

# Provide colors to enrichmentPlot
# colorEnrichmentMap(enrichPlot, pathways, colorOption) {
#   #
# }

# plot enrichment map from files generated by ActivePathways
plotEnrichmentMapFromFile <- function(gmtFile, pathwaysFile, algorithm, similarityCutoff, pvalueCutoff, k) {
  pathways <- data.table::fread(pathwaysFile)
  gmt <- ActivePathways::read.GMT(gmtFile)
  gmtData <- getDataFromGMT(gmt)
  scMatrix <- computeSCMatrix(algorithm = algorithm, 
                              gmt = gmt, 
                              ids = gmtData$ids, 
                              k = k)
  enrichPlot <- plotSimiScoreMatrix(simiScoreMatrix = scMatrix, 
                      similarityCutoff = similarityCutoff, 
                      lens = gmtData$lengths, 
                      pathwayNames = gmtData$pathwayNames,
                      pathways = pathways)
  return(enrichPlot)
}

# plot enrichment map from result of ActivePathways
plotEnrichmentMap <- function(gmt, enrichment, algorithm, similarityCutoff, pvalueCutoff, k) {
  pathways <- enrichment[, c("term.id", "term.name", "adjusted.p.val")]
  matchesColumns <- match(names(gmt), pathways$term.id) > 0
  matchesColumns[is.na(matchesColumns)] = FALSE 
  gmt <- gmt[matchesColumns]
  gmtData <- getDataFromGMT(gmt)
  scMatrix <- computeSCMatrix(algorithm = algorithm, 
                              gmt = gmt, 
                              ids = gmtData$ids, 
                              k = k)
  enrichPlot <- plotSimiScoreMatrix(simiScoreMatrix = scMatrix, 
                                    similarityCutoff = similarityCutoff, 
                                    pvalueCutoff = pvalueCutoff, 
                                    lens = gmtData$lengths, 
                                    pathwayNames = gmtData$pathwayNames,
                                    pathways = pathways)
  return(enrichPlot)
}



# scores <- read.table(
#   system.file('extdata', 'Adenocarcinoma_scores_subset.tsv', package = 'ActivePathways'),
#   header = TRUE, sep = '\t', row.names = 'Gene')
# scores <- as.matrix(scores)
# scores[is.na(scores)] <- 1
# gmt.file <- system.file('extdata', 'hsapiens_REAC_subset.gmt', package = 'ActivePathways')
# enrich <- ActivePathways(scores, gmt.file)
# gmt <- read.GMT(gmt.file)
# g <- plotEnrichmentMap(gmt = gmt, 
#                   enrichment = enrich, 
#                   algorithm = "jaccard", 
#                   similarityCutoff = 0.25, 
#                   pvalueCutoff = NULL, 
#                   k = 0.5)
# plot(g, vertex.label.cex = 0.6)
# 
# library(visNetwork)
# visNetwork::visIgraph(g)
